[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Environment variables that don't contain sensitive data
  NEXT_PUBLIC_SITE_URL = "https://baltzartandvardcursor.netlify.app"
  
  # Note: Supabase credentials should be set via Netlify UI environment variables
  # DO NOT hardcode sensitive credentials here - they should be set in Netlify UI

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

[functions]
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Auth callback must be handled by the Next.js app router
[[redirects]]
  from = "/auth/callback"
  to = "/auth/callback"
  status = 200
  force = true

# Handle auth callback with any query parameters
[[redirects]]
  from = "/auth/callback*"
  to = "/auth/callback:splat"
  status = 200
  force = true

# Catch-all rule for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 